language: python
sudo: false
dist: trusty
os: linux
ruby: 2.2.0
cache:
  - pip
  - bundler
install:
  - pip install -r requirements.txt
  - bundle install
script:
  - bundle exec danger
  - python hello_world.py
